name: Node.js Package

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash
    # working-directory: packages/pg

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc          
      - run: yarn install
      - run: yarn publish packages/pg
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}